# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ati/Desktop/code/lol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ati/Desktop/code/lol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ati/Desktop/code/lol/CMakeFiles /home/ati/Desktop/code/lol//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ati/Desktop/code/lol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ati/Desktop/code/lol/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named FastNoise

# Build rule for target.
FastNoise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FastNoise
.PHONY : FastNoise

# fast build rule for target.
FastNoise/fast:
	$(MAKE) $(MAKESILENT) -f lib/FastNoise2/src/CMakeFiles/FastNoise.dir/build.make lib/FastNoise2/src/CMakeFiles/FastNoise.dir/build
.PHONY : FastNoise/fast

#=============================================================================
# Target rules for targets named NoiseTool_RESOURCES-dependencies

# Build rule for target.
NoiseTool_RESOURCES-dependencies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NoiseTool_RESOURCES-dependencies
.PHONY : NoiseTool_RESOURCES-dependencies

# fast build rule for target.
NoiseTool_RESOURCES-dependencies/fast:
	$(MAKE) $(MAKESILENT) -f lib/FastNoise2/NoiseTool/CMakeFiles/NoiseTool_RESOURCES-dependencies.dir/build.make lib/FastNoise2/NoiseTool/CMakeFiles/NoiseTool_RESOURCES-dependencies.dir/build
.PHONY : NoiseTool_RESOURCES-dependencies/fast

#=============================================================================
# Target rules for targets named NoiseTool

# Build rule for target.
NoiseTool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NoiseTool
.PHONY : NoiseTool

# fast build rule for target.
NoiseTool/fast:
	$(MAKE) $(MAKESILENT) -f lib/FastNoise2/NoiseTool/CMakeFiles/NoiseTool.dir/build.make lib/FastNoise2/NoiseTool/CMakeFiles/NoiseTool.dir/build
.PHONY : NoiseTool/fast

#=============================================================================
# Target rules for targets named Corrade

# Build rule for target.
Corrade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Corrade
.PHONY : Corrade

# fast build rule for target.
Corrade/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/CMakeFiles/Corrade.dir/build.make _deps/corrade-build/src/Corrade/CMakeFiles/Corrade.dir/build
.PHONY : Corrade/fast

#=============================================================================
# Target rules for targets named CorradeContainers-headers

# Build rule for target.
CorradeContainers-headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CorradeContainers-headers
.PHONY : CorradeContainers-headers

# fast build rule for target.
CorradeContainers-headers/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/Containers/CMakeFiles/CorradeContainers-headers.dir/build.make _deps/corrade-build/src/Corrade/Containers/CMakeFiles/CorradeContainers-headers.dir/build
.PHONY : CorradeContainers-headers/fast

#=============================================================================
# Target rules for targets named CorradePluginManagerObjects

# Build rule for target.
CorradePluginManagerObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CorradePluginManagerObjects
.PHONY : CorradePluginManagerObjects

# fast build rule for target.
CorradePluginManagerObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/PluginManager/CMakeFiles/CorradePluginManagerObjects.dir/build.make _deps/corrade-build/src/Corrade/PluginManager/CMakeFiles/CorradePluginManagerObjects.dir/build
.PHONY : CorradePluginManagerObjects/fast

#=============================================================================
# Target rules for targets named CorradePluginManager

# Build rule for target.
CorradePluginManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CorradePluginManager
.PHONY : CorradePluginManager

# fast build rule for target.
CorradePluginManager/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/PluginManager/CMakeFiles/CorradePluginManager.dir/build.make _deps/corrade-build/src/Corrade/PluginManager/CMakeFiles/CorradePluginManager.dir/build
.PHONY : CorradePluginManager/fast

#=============================================================================
# Target rules for targets named CorradeUtilityObjects

# Build rule for target.
CorradeUtilityObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CorradeUtilityObjects
.PHONY : CorradeUtilityObjects

# fast build rule for target.
CorradeUtilityObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/Utility/CMakeFiles/CorradeUtilityObjects.dir/build.make _deps/corrade-build/src/Corrade/Utility/CMakeFiles/CorradeUtilityObjects.dir/build
.PHONY : CorradeUtilityObjects/fast

#=============================================================================
# Target rules for targets named CorradeUtility

# Build rule for target.
CorradeUtility: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CorradeUtility
.PHONY : CorradeUtility

# fast build rule for target.
CorradeUtility/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/Utility/CMakeFiles/CorradeUtility.dir/build.make _deps/corrade-build/src/Corrade/Utility/CMakeFiles/CorradeUtility.dir/build
.PHONY : CorradeUtility/fast

#=============================================================================
# Target rules for targets named corrade-rc

# Build rule for target.
corrade-rc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 corrade-rc
.PHONY : corrade-rc

# fast build rule for target.
corrade-rc/fast:
	$(MAKE) $(MAKESILENT) -f _deps/corrade-build/src/Corrade/Utility/CMakeFiles/corrade-rc.dir/build.make _deps/corrade-build/src/Corrade/Utility/CMakeFiles/corrade-rc.dir/build
.PHONY : corrade-rc/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named MagnumFlextGLObjects

# Build rule for target.
MagnumFlextGLObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumFlextGLObjects
.PHONY : MagnumFlextGLObjects

# fast build rule for target.
MagnumFlextGLObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/MagnumExternal/OpenGL/GL/CMakeFiles/MagnumFlextGLObjects.dir/build.make _deps/magnum-build/src/MagnumExternal/OpenGL/GL/CMakeFiles/MagnumFlextGLObjects.dir/build
.PHONY : MagnumFlextGLObjects/fast

#=============================================================================
# Target rules for targets named MagnumMathObjects

# Build rule for target.
MagnumMathObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumMathObjects
.PHONY : MagnumMathObjects

# fast build rule for target.
MagnumMathObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/CMakeFiles/MagnumMathObjects.dir/build.make _deps/magnum-build/src/Magnum/CMakeFiles/MagnumMathObjects.dir/build
.PHONY : MagnumMathObjects/fast

#=============================================================================
# Target rules for targets named MagnumObjects

# Build rule for target.
MagnumObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumObjects
.PHONY : MagnumObjects

# fast build rule for target.
MagnumObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/CMakeFiles/MagnumObjects.dir/build.make _deps/magnum-build/src/Magnum/CMakeFiles/MagnumObjects.dir/build
.PHONY : MagnumObjects/fast

#=============================================================================
# Target rules for targets named Magnum

# Build rule for target.
Magnum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Magnum
.PHONY : Magnum

# fast build rule for target.
Magnum/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/CMakeFiles/Magnum.dir/build.make _deps/magnum-build/src/Magnum/CMakeFiles/Magnum.dir/build
.PHONY : Magnum/fast

#=============================================================================
# Target rules for targets named MagnumAnimation

# Build rule for target.
MagnumAnimation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumAnimation
.PHONY : MagnumAnimation

# fast build rule for target.
MagnumAnimation/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Animation/CMakeFiles/MagnumAnimation.dir/build.make _deps/magnum-build/src/Magnum/Animation/CMakeFiles/MagnumAnimation.dir/build
.PHONY : MagnumAnimation/fast

#=============================================================================
# Target rules for targets named MagnumMath

# Build rule for target.
MagnumMath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumMath
.PHONY : MagnumMath

# fast build rule for target.
MagnumMath/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Math/CMakeFiles/MagnumMath.dir/build.make _deps/magnum-build/src/Magnum/Math/CMakeFiles/MagnumMath.dir/build
.PHONY : MagnumMath/fast

#=============================================================================
# Target rules for targets named MagnumMathAlgorithms

# Build rule for target.
MagnumMathAlgorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumMathAlgorithms
.PHONY : MagnumMathAlgorithms

# fast build rule for target.
MagnumMathAlgorithms/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Math/Algorithms/CMakeFiles/MagnumMathAlgorithms.dir/build.make _deps/magnum-build/src/Magnum/Math/Algorithms/CMakeFiles/MagnumMathAlgorithms.dir/build
.PHONY : MagnumMathAlgorithms/fast

#=============================================================================
# Target rules for targets named MagnumPlatformObjects

# Build rule for target.
MagnumPlatformObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumPlatformObjects
.PHONY : MagnumPlatformObjects

# fast build rule for target.
MagnumPlatformObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/build.make _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/build
.PHONY : MagnumPlatformObjects/fast

#=============================================================================
# Target rules for targets named MagnumGlfwApplication

# Build rule for target.
MagnumGlfwApplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumGlfwApplication
.PHONY : MagnumGlfwApplication

# fast build rule for target.
MagnumGlfwApplication/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumGlfwApplication.dir/build.make _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumGlfwApplication.dir/build
.PHONY : MagnumGlfwApplication/fast

#=============================================================================
# Target rules for targets named MagnumGlxContextObjects

# Build rule for target.
MagnumGlxContextObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumGlxContextObjects
.PHONY : MagnumGlxContextObjects

# fast build rule for target.
MagnumGlxContextObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumGlxContextObjects.dir/build.make _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumGlxContextObjects.dir/build
.PHONY : MagnumGlxContextObjects/fast

#=============================================================================
# Target rules for targets named MagnumPlatform

# Build rule for target.
MagnumPlatform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumPlatform
.PHONY : MagnumPlatform

# fast build rule for target.
MagnumPlatform/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumPlatform.dir/build.make _deps/magnum-build/src/Magnum/Platform/CMakeFiles/MagnumPlatform.dir/build
.PHONY : MagnumPlatform/fast

#=============================================================================
# Target rules for targets named MagnumDebugToolsObjects

# Build rule for target.
MagnumDebugToolsObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumDebugToolsObjects
.PHONY : MagnumDebugToolsObjects

# fast build rule for target.
MagnumDebugToolsObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/DebugTools/CMakeFiles/MagnumDebugToolsObjects.dir/build.make _deps/magnum-build/src/Magnum/DebugTools/CMakeFiles/MagnumDebugToolsObjects.dir/build
.PHONY : MagnumDebugToolsObjects/fast

#=============================================================================
# Target rules for targets named MagnumDebugTools

# Build rule for target.
MagnumDebugTools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumDebugTools
.PHONY : MagnumDebugTools

# fast build rule for target.
MagnumDebugTools/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/DebugTools/CMakeFiles/MagnumDebugTools.dir/build.make _deps/magnum-build/src/Magnum/DebugTools/CMakeFiles/MagnumDebugTools.dir/build
.PHONY : MagnumDebugTools/fast

#=============================================================================
# Target rules for targets named MagnumGLObjects

# Build rule for target.
MagnumGLObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumGLObjects
.PHONY : MagnumGLObjects

# fast build rule for target.
MagnumGLObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/GL/CMakeFiles/MagnumGLObjects.dir/build.make _deps/magnum-build/src/Magnum/GL/CMakeFiles/MagnumGLObjects.dir/build
.PHONY : MagnumGLObjects/fast

#=============================================================================
# Target rules for targets named MagnumGL

# Build rule for target.
MagnumGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumGL
.PHONY : MagnumGL

# fast build rule for target.
MagnumGL/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/GL/CMakeFiles/MagnumGL.dir/build.make _deps/magnum-build/src/Magnum/GL/CMakeFiles/MagnumGL.dir/build
.PHONY : MagnumGL/fast

#=============================================================================
# Target rules for targets named MagnumPrimitives

# Build rule for target.
MagnumPrimitives: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumPrimitives
.PHONY : MagnumPrimitives

# fast build rule for target.
MagnumPrimitives/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/build.make _deps/magnum-build/src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/build
.PHONY : MagnumPrimitives/fast

#=============================================================================
# Target rules for targets named MagnumSceneGraphObjects

# Build rule for target.
MagnumSceneGraphObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumSceneGraphObjects
.PHONY : MagnumSceneGraphObjects

# fast build rule for target.
MagnumSceneGraphObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraphObjects.dir/build.make _deps/magnum-build/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraphObjects.dir/build
.PHONY : MagnumSceneGraphObjects/fast

#=============================================================================
# Target rules for targets named MagnumSceneGraph

# Build rule for target.
MagnumSceneGraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumSceneGraph
.PHONY : MagnumSceneGraph

# fast build rule for target.
MagnumSceneGraph/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraph.dir/build.make _deps/magnum-build/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraph.dir/build
.PHONY : MagnumSceneGraph/fast

#=============================================================================
# Target rules for targets named MagnumShaders_RESOURCES_GL-dependencies

# Build rule for target.
MagnumShaders_RESOURCES_GL-dependencies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumShaders_RESOURCES_GL-dependencies
.PHONY : MagnumShaders_RESOURCES_GL-dependencies

# fast build rule for target.
MagnumShaders_RESOURCES_GL-dependencies/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Shaders/CMakeFiles/MagnumShaders_RESOURCES_GL-dependencies.dir/build.make _deps/magnum-build/src/Magnum/Shaders/CMakeFiles/MagnumShaders_RESOURCES_GL-dependencies.dir/build
.PHONY : MagnumShaders_RESOURCES_GL-dependencies/fast

#=============================================================================
# Target rules for targets named MagnumShadersObjects

# Build rule for target.
MagnumShadersObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumShadersObjects
.PHONY : MagnumShadersObjects

# fast build rule for target.
MagnumShadersObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Shaders/CMakeFiles/MagnumShadersObjects.dir/build.make _deps/magnum-build/src/Magnum/Shaders/CMakeFiles/MagnumShadersObjects.dir/build
.PHONY : MagnumShadersObjects/fast

#=============================================================================
# Target rules for targets named MagnumShaders

# Build rule for target.
MagnumShaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumShaders
.PHONY : MagnumShaders

# fast build rule for target.
MagnumShaders/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/build.make _deps/magnum-build/src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/build
.PHONY : MagnumShaders/fast

#=============================================================================
# Target rules for targets named MagnumShaderTools

# Build rule for target.
MagnumShaderTools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumShaderTools
.PHONY : MagnumShaderTools

# fast build rule for target.
MagnumShaderTools/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/ShaderTools/CMakeFiles/MagnumShaderTools.dir/build.make _deps/magnum-build/src/Magnum/ShaderTools/CMakeFiles/MagnumShaderTools.dir/build
.PHONY : MagnumShaderTools/fast

#=============================================================================
# Target rules for targets named MagnumTradeObjects

# Build rule for target.
MagnumTradeObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumTradeObjects
.PHONY : MagnumTradeObjects

# fast build rule for target.
MagnumTradeObjects/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Trade/CMakeFiles/MagnumTradeObjects.dir/build.make _deps/magnum-build/src/Magnum/Trade/CMakeFiles/MagnumTradeObjects.dir/build
.PHONY : MagnumTradeObjects/fast

#=============================================================================
# Target rules for targets named MagnumTrade

# Build rule for target.
MagnumTrade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumTrade
.PHONY : MagnumTrade

# fast build rule for target.
MagnumTrade/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-build/src/Magnum/Trade/CMakeFiles/MagnumTrade.dir/build.make _deps/magnum-build/src/Magnum/Trade/CMakeFiles/MagnumTrade.dir/build
.PHONY : MagnumTrade/fast

#=============================================================================
# Target rules for targets named MagnumImGuiIntegration

# Build rule for target.
MagnumImGuiIntegration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnumImGuiIntegration
.PHONY : MagnumImGuiIntegration

# fast build rule for target.
MagnumImGuiIntegration/fast:
	$(MAKE) $(MAKESILENT) -f _deps/magnum-integration-build/src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/build.make _deps/magnum-integration-build/src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/build
.PHONY : MagnumImGuiIntegration/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f lib/glad/CMakeFiles/glad.dir/build.make lib/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

src/game/world/Chunk.o: src/game/world/Chunk.cpp.o
.PHONY : src/game/world/Chunk.o

# target to build an object file
src/game/world/Chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/Chunk.cpp.o
.PHONY : src/game/world/Chunk.cpp.o

src/game/world/Chunk.i: src/game/world/Chunk.cpp.i
.PHONY : src/game/world/Chunk.i

# target to preprocess a source file
src/game/world/Chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/Chunk.cpp.i
.PHONY : src/game/world/Chunk.cpp.i

src/game/world/Chunk.s: src/game/world/Chunk.cpp.s
.PHONY : src/game/world/Chunk.s

# target to generate assembly for a file
src/game/world/Chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/Chunk.cpp.s
.PHONY : src/game/world/Chunk.cpp.s

src/game/world/World.o: src/game/world/World.cpp.o
.PHONY : src/game/world/World.o

# target to build an object file
src/game/world/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/World.cpp.o
.PHONY : src/game/world/World.cpp.o

src/game/world/World.i: src/game/world/World.cpp.i
.PHONY : src/game/world/World.i

# target to preprocess a source file
src/game/world/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/World.cpp.i
.PHONY : src/game/world/World.cpp.i

src/game/world/World.s: src/game/world/World.cpp.s
.PHONY : src/game/world/World.s

# target to generate assembly for a file
src/game/world/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/World.cpp.s
.PHONY : src/game/world/World.cpp.s

src/game/world/block.o: src/game/world/block.cpp.o
.PHONY : src/game/world/block.o

# target to build an object file
src/game/world/block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/block.cpp.o
.PHONY : src/game/world/block.cpp.o

src/game/world/block.i: src/game/world/block.cpp.i
.PHONY : src/game/world/block.i

# target to preprocess a source file
src/game/world/block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/block.cpp.i
.PHONY : src/game/world/block.cpp.i

src/game/world/block.s: src/game/world/block.cpp.s
.PHONY : src/game/world/block.s

# target to generate assembly for a file
src/game/world/block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/game/world/block.cpp.s
.PHONY : src/game/world/block.cpp.s

src/input/Input.o: src/input/Input.cpp.o
.PHONY : src/input/Input.o

# target to build an object file
src/input/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/input/Input.cpp.o
.PHONY : src/input/Input.cpp.o

src/input/Input.i: src/input/Input.cpp.i
.PHONY : src/input/Input.i

# target to preprocess a source file
src/input/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/input/Input.cpp.i
.PHONY : src/input/Input.cpp.i

src/input/Input.s: src/input/Input.cpp.s
.PHONY : src/input/Input.s

# target to generate assembly for a file
src/input/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/input/Input.cpp.s
.PHONY : src/input/Input.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/vendor/glm/detail/glm.o: src/vendor/glm/detail/glm.cpp.o
.PHONY : src/vendor/glm/detail/glm.o

# target to build an object file
src/vendor/glm/detail/glm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/glm/detail/glm.cpp.o
.PHONY : src/vendor/glm/detail/glm.cpp.o

src/vendor/glm/detail/glm.i: src/vendor/glm/detail/glm.cpp.i
.PHONY : src/vendor/glm/detail/glm.i

# target to preprocess a source file
src/vendor/glm/detail/glm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/glm/detail/glm.cpp.i
.PHONY : src/vendor/glm/detail/glm.cpp.i

src/vendor/glm/detail/glm.s: src/vendor/glm/detail/glm.cpp.s
.PHONY : src/vendor/glm/detail/glm.s

# target to generate assembly for a file
src/vendor/glm/detail/glm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/glm/detail/glm.cpp.s
.PHONY : src/vendor/glm/detail/glm.cpp.s

src/vendor/imgui/imgui.o: src/vendor/imgui/imgui.cpp.o
.PHONY : src/vendor/imgui/imgui.o

# target to build an object file
src/vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui.cpp.o
.PHONY : src/vendor/imgui/imgui.cpp.o

src/vendor/imgui/imgui.i: src/vendor/imgui/imgui.cpp.i
.PHONY : src/vendor/imgui/imgui.i

# target to preprocess a source file
src/vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui.cpp.i
.PHONY : src/vendor/imgui/imgui.cpp.i

src/vendor/imgui/imgui.s: src/vendor/imgui/imgui.cpp.s
.PHONY : src/vendor/imgui/imgui.s

# target to generate assembly for a file
src/vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui.cpp.s
.PHONY : src/vendor/imgui/imgui.cpp.s

src/vendor/imgui/imgui_demo.o: src/vendor/imgui/imgui_demo.cpp.o
.PHONY : src/vendor/imgui/imgui_demo.o

# target to build an object file
src/vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_demo.cpp.o
.PHONY : src/vendor/imgui/imgui_demo.cpp.o

src/vendor/imgui/imgui_demo.i: src/vendor/imgui/imgui_demo.cpp.i
.PHONY : src/vendor/imgui/imgui_demo.i

# target to preprocess a source file
src/vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_demo.cpp.i
.PHONY : src/vendor/imgui/imgui_demo.cpp.i

src/vendor/imgui/imgui_demo.s: src/vendor/imgui/imgui_demo.cpp.s
.PHONY : src/vendor/imgui/imgui_demo.s

# target to generate assembly for a file
src/vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_demo.cpp.s
.PHONY : src/vendor/imgui/imgui_demo.cpp.s

src/vendor/imgui/imgui_draw.o: src/vendor/imgui/imgui_draw.cpp.o
.PHONY : src/vendor/imgui/imgui_draw.o

# target to build an object file
src/vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_draw.cpp.o
.PHONY : src/vendor/imgui/imgui_draw.cpp.o

src/vendor/imgui/imgui_draw.i: src/vendor/imgui/imgui_draw.cpp.i
.PHONY : src/vendor/imgui/imgui_draw.i

# target to preprocess a source file
src/vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_draw.cpp.i
.PHONY : src/vendor/imgui/imgui_draw.cpp.i

src/vendor/imgui/imgui_draw.s: src/vendor/imgui/imgui_draw.cpp.s
.PHONY : src/vendor/imgui/imgui_draw.s

# target to generate assembly for a file
src/vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_draw.cpp.s
.PHONY : src/vendor/imgui/imgui_draw.cpp.s

src/vendor/imgui/imgui_impl_glfw_gl3.o: src/vendor/imgui/imgui_impl_glfw_gl3.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_glfw_gl3.o

# target to build an object file
src/vendor/imgui/imgui_impl_glfw_gl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_glfw_gl3.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_glfw_gl3.cpp.o

src/vendor/imgui/imgui_impl_glfw_gl3.i: src/vendor/imgui/imgui_impl_glfw_gl3.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_glfw_gl3.i

# target to preprocess a source file
src/vendor/imgui/imgui_impl_glfw_gl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_glfw_gl3.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_glfw_gl3.cpp.i

src/vendor/imgui/imgui_impl_glfw_gl3.s: src/vendor/imgui/imgui_impl_glfw_gl3.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_glfw_gl3.s

# target to generate assembly for a file
src/vendor/imgui/imgui_impl_glfw_gl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_glfw_gl3.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_glfw_gl3.cpp.s

src/vendor/stb_image/stb_image.o: src/vendor/stb_image/stb_image.cpp.o
.PHONY : src/vendor/stb_image/stb_image.o

# target to build an object file
src/vendor/stb_image/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/stb_image/stb_image.cpp.o
.PHONY : src/vendor/stb_image/stb_image.cpp.o

src/vendor/stb_image/stb_image.i: src/vendor/stb_image/stb_image.cpp.i
.PHONY : src/vendor/stb_image/stb_image.i

# target to preprocess a source file
src/vendor/stb_image/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/stb_image/stb_image.cpp.i
.PHONY : src/vendor/stb_image/stb_image.cpp.i

src/vendor/stb_image/stb_image.s: src/vendor/stb_image/stb_image.cpp.s
.PHONY : src/vendor/stb_image/stb_image.s

# target to generate assembly for a file
src/vendor/stb_image/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/stb_image/stb_image.cpp.s
.PHONY : src/vendor/stb_image/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Corrade"
	@echo "... CorradeContainers-headers"
	@echo "... MagnumAnimation"
	@echo "... MagnumMath"
	@echo "... MagnumMathAlgorithms"
	@echo "... MagnumPlatform"
	@echo "... MagnumShaders_RESOURCES_GL-dependencies"
	@echo "... NoiseTool_RESOURCES-dependencies"
	@echo "... CorradePluginManager"
	@echo "... CorradePluginManagerObjects"
	@echo "... CorradeUtility"
	@echo "... CorradeUtilityObjects"
	@echo "... FastNoise"
	@echo "... Magnum"
	@echo "... MagnumDebugTools"
	@echo "... MagnumDebugToolsObjects"
	@echo "... MagnumFlextGLObjects"
	@echo "... MagnumGL"
	@echo "... MagnumGLObjects"
	@echo "... MagnumGlfwApplication"
	@echo "... MagnumGlxContextObjects"
	@echo "... MagnumImGuiIntegration"
	@echo "... MagnumMathObjects"
	@echo "... MagnumObjects"
	@echo "... MagnumPlatformObjects"
	@echo "... MagnumPrimitives"
	@echo "... MagnumSceneGraph"
	@echo "... MagnumSceneGraphObjects"
	@echo "... MagnumShaderTools"
	@echo "... MagnumShaders"
	@echo "... MagnumShadersObjects"
	@echo "... MagnumTrade"
	@echo "... MagnumTradeObjects"
	@echo "... NoiseTool"
	@echo "... corrade-rc"
	@echo "... glad"
	@echo "... glfw"
	@echo "... main"
	@echo "... src/game/world/Chunk.o"
	@echo "... src/game/world/Chunk.i"
	@echo "... src/game/world/Chunk.s"
	@echo "... src/game/world/World.o"
	@echo "... src/game/world/World.i"
	@echo "... src/game/world/World.s"
	@echo "... src/game/world/block.o"
	@echo "... src/game/world/block.i"
	@echo "... src/game/world/block.s"
	@echo "... src/input/Input.o"
	@echo "... src/input/Input.i"
	@echo "... src/input/Input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/vendor/glm/detail/glm.o"
	@echo "... src/vendor/glm/detail/glm.i"
	@echo "... src/vendor/glm/detail/glm.s"
	@echo "... src/vendor/imgui/imgui.o"
	@echo "... src/vendor/imgui/imgui.i"
	@echo "... src/vendor/imgui/imgui.s"
	@echo "... src/vendor/imgui/imgui_demo.o"
	@echo "... src/vendor/imgui/imgui_demo.i"
	@echo "... src/vendor/imgui/imgui_demo.s"
	@echo "... src/vendor/imgui/imgui_draw.o"
	@echo "... src/vendor/imgui/imgui_draw.i"
	@echo "... src/vendor/imgui/imgui_draw.s"
	@echo "... src/vendor/imgui/imgui_impl_glfw_gl3.o"
	@echo "... src/vendor/imgui/imgui_impl_glfw_gl3.i"
	@echo "... src/vendor/imgui/imgui_impl_glfw_gl3.s"
	@echo "... src/vendor/stb_image/stb_image.o"
	@echo "... src/vendor/stb_image/stb_image.i"
	@echo "... src/vendor/stb_image/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ati/Desktop/code/lol/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

